


KNOWLEDGE_BASE = {
    "print": "Outputs text to the console.",
    "len": "Returns the number of items in a container.",
    "sum": "Returns the sum of all items in an iterable.",
    "max": "Returns the largest item in an iterable or two or more arguments.",
    "min": "Returns the smallest item in an iterable or two or more arguments.",
    "range": "Generates a sequence of numbers from start to stop (exclusive).",
    "sorted": "Returns a new sorted list from the items in an iterable.",
    "open": "Opens a file and returns a file object.",
    "input": "Reads a line of input from the user.",
    "map": "Applies a function to all items in an input list.",
    "filter": "Constructs an iterator from items in iterable for which function returns true.",
    "set": "Creates a set object, which is an unordered collection of unique items.",
    "frozenset": "Returns an immutable version of a set.",
    "list": "Creates a list object, a mutable sequence.",
    "tuple": "Creates a tuple object, an immutable sequence.",
    "dict": "Creates a dictionary object, a collection of key-value pairs.",
    "str": "Creates a string object or converts an object to a string.",
    "int": "Converts an object to an integer or returns an integer object.",
    "float": "Converts an object to a floating-point number or returns a float object.",
    "complex": "Creates a complex number or converts an object to a complex number.",
    "bool": "Returns a Boolean value, True or False.",
    "bin": "Converts an integer to its binary representation as a string.",
    "hex": "Converts an integer to its hexadecimal representation as a string.",
    "oct": "Converts an integer to its octal representation as a string.",
    "id": "Returns the unique identifier of an object.",
    "hash": "Returns the hash value of an object, if it has one.",
    "format": "Formats a value with a specified format string.",
    "chr": "Returns the character corresponding to an ASCII value.",
    "ord": "Returns the ASCII value corresponding to a character.",
    "repr": "Returns a string containing a printable representation of an object.",
    "globals": "Returns a dictionary of the current global symbol table.",
    "locals": "Returns a dictionary of the current local symbol table.",
    "memoryview": "Returns a memory view object of a given object.",
    "staticmethod": "Converts a method into a static method.",
    "classmethod": "Converts a method into a class method.",
    "property": "Returns a property object, which can define getters, setters, and deleters."    
    "zip": "Combines two or more iterables into tuples.",
    "any": "Returns True if any element of an iterable is true.",
    "all": "Returns True if all elements of an iterable are true.",
    "enumerate": "Returns an enumerate object that adds a counter to an iterable.",
    "abs": "Returns the absolute value of a number.",
    "round": "Rounds a number to a specified number of decimal places.",
    "isinstance": "Checks if an object is an instance or subclass of a class.",
    "type": "Returns the type of an object.",
    "dir": "Returns a list of valid attributes for an object.",
    "help": "Displays help information for an object.",
    "eval": "Parses and evaluates a Python expression as a string.",
    "exec": "Executes dynamically generated Python code.",
    "reversed": "Returns a reverse iterator for a sequence.",
    "pow": "Returns the result of a number raised to a power.",
    "divmod": "Returns a tuple containing the quotient and remainder of a division."
}

